from util_classes import Color   
    
def ANSI(string: str, **kwargs) -> str:
    if kwargs.get("red", False) == True:
        string = Color.RED + string
    if kwargs.get("cyan", False) == True:
        string = Color.CYAN + string
    if kwargs.get("add_end_ansi", True) == False: 
        return string
    if kwargs.get("bold", False) == True:
        string = Color.BOLD + string
    if kwargs.get("dark_gray", False) == True:
        string = Color.DARK_GRAY + string
    if kwargs.get("italics", False) == True:
        string = Color.ITALICS + string
    if kwargs.get("underline", False) == True:
        string = Color.UNDERLINE + string
    if kwargs.get("white_background", False) == True:
        string = Color.WHITE_BACKGROUND + string
    if kwargs.get("black", False) == True:
        string = Color.BLACK + string
    if kwargs.get("strike_through", False) == True:
        string = Color.STRIKE_THROUGH + string
    if kwargs.get("double_underline", False) == True:
        string = Color.DOUBLE_UNDERLINE + string
    if kwargs.get("red_background", False) == True:
        string = Color.RED_BACKGROUND + string
    if kwargs.get("mint_background", False) == True:
        string = Color.MINT_BACKGROUND + string
    if kwargs.get("yellow_background", False) == True:
        string = Color.YELLOW_BACKGROUND + string
    if kwargs.get("blue_background", False) == True:
        string = Color.BlUE_BACKGROUND + string
    if kwargs.get("magenta_background", False) == True:
        string = Color.MAGENTA_BACKGROUND + string
    if kwargs.get("cyan_background", False) == True:
        string = Color.CYAN_BACKGROUND + string
    if kwargs.get("white_background", False) == True:
        string = Color.WHITE_BACKGROUND + string
    if kwargs.get("overline", False) == True:
        string = Color.OVER_LINE + string
    if kwargs.get("light_red", False) == True:
        string = Color.LIGHT_RED + string
    if kwargs.get("gray_background", False) == True:
        string = Color.GRAY_BACKGROUND + string
    if kwargs.get("light_red_background", False) == True:
        string = Color.LIGHT_RED_BACKGROUND + string
    if kwargs.get("gray", False) == True:
        string = Color.GRAY + string
    if kwargs.get("mint", False) == True:
        string = Color.MINT + string
    if kwargs.get("yellow", False) == True:
        string = Color.YELLOW + string
    if kwargs.get("magenta", False) == True:
        string = Color.MAGENTA + string
    if kwargs.get("white", False) == True:
        string = Color.WHITE + string
    if kwargs.get("light_red", False) == True:
        string = Color.LIGHT_RED + string
    if kwargs.get("light_red_background", False) == True:
        string = Color.LIGHT_RED_BACKGROUND + string
    if kwargs.get("gray_background", False) == True:
        string = Color.GRAY_BACKGROUND + string
    if kwargs.get("light_blue", False) == True:
        string = Color.CYAN + string
    return string + Color.END_ANSI
