import setuptools

setuptools.setup(
    name='func',
    version='1.0.0',
    author='Alexander Cook',
    author_email='alchemerxander@gmail.com',
    description='A collection of utility functions',
    long_description='A list of utility functions that I use for every project',
    long_description_content_type='text/markdown',
    url='https://github.com/SirAlchemer/func/',
    project_urls={
        'Documentation': 'https://github.com/SirAlchemer/func/blob/main/README.md',
        'Source Code': 'https://github.com/SirAlchemer/func/',
        'Issue Tracker': 'https://github.com/SirAlchemer/func/issues',
    },
    packages=setuptools.find_packages(),
    install_requires=[],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Utilities',
    ],
    keywords='utils utility functions',
    python_requires='>=3.6',
)
